services:
  node:
      container_name: react-native
      hostname: react-native
      build:
        context: ./
        dockerfile: ./dockerfile
        target: development
      volumes:
        - ${APP_DIRECTORY}:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - ${SERVER_PORT_RN}:${SERVER_PORT_RN}
        - ${SERVER_PORT_1}:${SERVER_PORT_1}
        - ${SERVER_PORT_2}:${SERVER_PORT_2}
        - ${SERVER_PORT_3}:${SERVER_PORT_3}
        - ${SERVER_PORT_4}:${SERVER_PORT_4}
        - 3000:3000
      # command: yarn run start:dev
      command: sleep infinity
      env_file:
        - .env
    
